### ISSUE TITLE
Anemometer

### ISSUE THREAD

**Issue by alp-kudzai** [erikflowers/weather-icons#256] opened 2022-04-02 08:00 UTC
Please add an Anemometer icon for wind speed.

**Comment by fox91** [comment] 2022-04-02 08:59
Duplicate of #175

**Closed as completed by fox91** 2022-04-02 08:59 UTC
Labels: duplicate, new icon

**Comment by fox91** [comment] 2022-04-02 09:01
Hi @alp-kudzai, this is an open project, feel free to contribute with a new icon if you can!
Thanks

**Comment by alp-kudzai** [comment] 2022-04-03 06:19
I will see what I can do.
